# 项目相关配置
ruoyi:
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/cache/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn
    xin.jiangqiang: debug

# Spring配置
spring:
  # 数据源配置
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://router.jiangqiang.xin:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        #加密的密码
        password: KTCDCM0GkaH22lsI7e5F6hgm4AgR55HakdVuBX//zqDcXACRdmQJGSxvAv5oXAyGcBfJv+cybMj2G8KDE3+VoQ==
      filter:
        config:
          # 是否配置加密
          enabled: true
      #加密公钥
      connectProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAI8d5hKBWLFOcb2qaOgdLOCgIycr4C1AbYRWCwp4sJJlXc4qQKScORnxQlL7+Y/Ecr1bImv19UFQ8DCem21AsYsCAwEAAQ==
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: ruoyi
        login-password: 123456
  # redis 配置
  redis:
    # 地址
    host: 192.168.1.2
    # 端口，默认为6379
    port: 6379
    # 密码
    password: suixin
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30


# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

